# Generated by Django 3.2 on 2022-12-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='quantity',
        ),
    ]
